viewcomponent:
  localDevelopment: true
supabase:
  projectId: tdvmeydbgpulquximxzc
  anonKey: ${SUPABASE_ANON_KEY}
  databasePassword: ${SUPABASE_DATABASE_PW}
  jwtSecret: ${SUPABASE_JWT_SECRET}
  successfulLoginRedirectPage: /tables
  passwordRecoveryPage: /updatePassword
  unauthenticatedPage: /unauthenticated
  unauthorizedPage: /unauthorizedPage
  sslOnly: false

  public:
    get:
      - "/"
      - "/api/user/logout"
      - "/js/**"
      - "/error"
      - "/unauthenticated"
      - "/lineChartComponent"
      - "/tables"
      - "/forms"
      - "/tabbed"
      - "/calendar"
      - "/login"
      - "/register"
      - "/403"
      - "/favicon.ico"
      - "/error"
      - "/resetPassword"
      - "/unauthenticated"
      - "/unauthorized"
    put:
      - "/api/person"
    post:
      - "/api/user/register"
      - "/api/user/login"
      - "/api/user/jwt"
      - "/api/user/sendPasswordResetEmail"
logging:
  level:
    org.springframework.web: DEBUG